force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ValidateAppointment.cls
public class ValidateAppointment {
    public static void checkTime(List<Appointment__c> newAppointments)
    {      
        Set<Id> appointmentIds = new Set<Id>();
        for(Appointment__c a : newAppointments)
        {
            appointmentIds.add(a.Doctor__c);
        }
        integer numOfApps = newAppointments.size();
        List <Appointment__c> times = [SELECT Time__c,Date__c FROM Appointment__c WHERE Doctor__c=:appointmentIds LIMIT :numOfApps];
       //  List <Appointment__c> dates = [SELECT Date__c FROM Appointment__c WHERE Id=:appointmentIds];
System.debug('times and dates : ' + times);
        
        for(Appointment__c a : times)
        {
            System.debug('in first for loop : ');

            for(Appointment__c app: newAppointments)
            {
           System.debug('in second : ');

                if(app.Time__c==a.Time__c && app.Date__c==a.Date__c)
                {
                               System.debug('record is not inserting : ');

                    app.addError('Sorry the selected doctor is busy at that time, Please pick a different time.');
                }
            }
        }
    }

}