force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Supported_Illnesses__c.field-meta.xml
<CustomField>
    <fullName>Supported_Illnesses__c</fullName>
    <label>Supported Illnesses</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flu</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Fever</fullName>
            </value>
            <value>
                <fullName>Skin Condition</fullName>
            </value>
            <value>
                <fullName>Cancer</fullName>
            </value>
            <value>
                <fullName>Gastrointestinal Illnesses</fullName>
            </value>
            <value>
                <fullName>Vertigo</fullName>
            </value>
            <value>
                <fullName>Headaches</fullName>
            </value>
            <value>
                <fullName>Eye Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/DoctorAndAppointmentController.cls
public class DoctorAndAppointmentController {
    public boolean settingAppointment{
        get;
        set;
    }
    
    public String appointmentName{
        get;
        set {
            appointmentName = value;
            System.debug('Appointment Name: ' + appointmentName);
        }
    }
    
    public date appointmentDate{
        get;
        set;
    }
    
    public time appointmentTime{
        get;
        set;
    }
    
    
        public String doctorName
    {
        get;
        //NOTE : when expanding a setter within a property you have to explicitly set its value 
        set{
            doctorName = value;
        
        }
    }

    public String cityName
    {
        get;
        set{
            cityName = value;
        }
    }
    //retrieved doctors
    public List<Doctor__c> doctors
    {
        get; 
        set{
            doctors = value;
            List<SelectOption> names = new List<SelectOption>(); //we will use this to automatically populate this.doctorNames
            for (Doctor__c doctor : doctors){
                names.add(new SelectOption(doctor.Name, doctor.Name + ', Address: ' + doctor.Address__c + ', Treats: ' + doctor.Supported_Illnesses__c));
            }
            this.doctorNames = names; //set doctorNames
        }
    }
    
    public List<SelectOption> doctorNames{
        //if the user has not yet searched for doctors the list of doctors should say none selected
        get{
            SelectOption defaultOption = new SelectOption('default', 'None Selected'); 
            if(doctorNames == null){ // user has not yet searched for doctors
                return new List<SelectOption>{defaultOption}; 
            }
            return doctorNames;
        }
            
        set;
    }
    
    public String selectedDoctorName{
        get;
        set{
            selectedDoctorName = value;
            Doctor__c selectedDoctor = [SELECT id, Name FROM Doctor__c WHERE Name =: selectedDoctorName];
            chosenDoctorId = selectedDoctor.id;
        }
    }
    
    public Id chosenDoctorId{
        get; 
        set{
            chosenDoctorId = value;
            System.debug('chosenDoctorId has been set to:' + chosenDoctorId);
        }
        
    }
    //query for doctors based on user input of name and illness
    public void getDoctors()
    {
        String searchCriteria = doctorName + '%';
        String filterCriteria = '%' + cityName + '%';
        System.debug('Search criteria:' + searchCriteria);
        doctors = [SELECT Name,Address__c,Supported_Illnesses__c FROM Doctor__c WHere Name Like :searchCriteria AND Address__c Like :filterCriteria];
    }
    
    //take users to 
    public void makeAppointment(){
        System.debug('chosenDoctorId is:'+chosenDoctorId);
        this.settingAppointment = true;
        //return Page.SetAppointment1;
    }
    
    //inputs new appointment with selected doctor, date and time
    public PageReference saveAppointment(){
        system.debug('save is called');
        Appointment__c appointment = new Appointment__c(Name=appointmentName, time__c=appointmentTime, date__c=appointmentDate, Doctor__c=chosenDoctorId);
        system.debug('appointment was created');
        insert appointment;
        system.debug('appointment was inserted');
        PageReference pg = new PageReference('/'+ appointment.Id);
        pg.setRedirect(true);
        return pg; 
    }

}