force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Supported_Illnesses__c.field-meta.xml
<CustomField>
    <fullName>Supported_Illnesses__c</fullName>
    <label>Supported Illnesses</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flu</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Fever</fullName>
            </value>
            <value>
                <fullName>Skin Condition</fullName>
            </value>
            <value>
                <fullName>Cancer</fullName>
            </value>
            <value>
                <fullName>Gastrointestinal Illnesses</fullName>
            </value>
            <value>
                <fullName>Vertigo</fullName>
            </value>
            <value>
                <fullName>Headaches</fullName>
            </value>
            <value>
                <fullName>Eye Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/GetDoctors1.cls
public class GetDoctors1 {	
    
    public GetDoctors1(ApexPages.StandardController stdController) {
            	 String theName = System.currentPagereference().getParameters().get('name');

    }

	public String doctorName
    {
        get;
        //NOTE : when expanding a setter within a property you have to explicitly set its value 
        set{
            doctorName = value;
        
        }
    }

    public String cityName
    {
		get;
        set{
            cityName = value;
        }
    }
    //retrieved doctors
    public List<Doctor__c> doctors
    {
        get; set;
    }
    //query for doctors based on user input of name and illness
    public void getDoctors()
    {
        String searchCriteria = doctorName + '%';
        String filterCriteria = '%' + cityName + '%';
        System.debug('Search criteria:' + searchCriteria);
        doctors = [SELECT Name,Address__c,Supported_Illnesses__c FROM Doctor__c WHere Name Like :searchCriteria AND Address__c Like :filterCriteria];
    }

}